# Generated by Django 5.2.1 on 2025-06-17 08:58

import django.core.validators
import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='prescription',
            field=models.ImageField(upload_to='prescriptions/', validators=[hospital.models.validate_file_size, hospital.models.validate_file_type, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
