# Generated by Django 5.2.1 on 2025-06-02 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'patient'}, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
