# Generated by Django 5.2.1 on 2025-06-02 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_user_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
