# Generated by Django 5.2.1 on 2025-06-02 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_reminder_doctor_reminder_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedlink',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
