# Generated by Django 5.2.1 on 2025-06-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_reminder_user_alter_reminder_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_delete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_set_reminders',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_share',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
