# Generated by Django 5.2.1 on 2025-06-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_user_can_delete_user_can_set_reminders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10),
        ),
    ]
