# Generated by Django 5.2.1 on 2025-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlink',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
